---
title: "Sensitivity Analyses: Adjustment for NOAA Climate Zone"
author: "Maggie Li (ml4424)"
date: "4/13/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load libraries}
library(tidyverse)
library(gridExtra)
library(grid)
library(ggplot2)
library(lattice)
library(lme4)
library(gamm4)
```

```{r Read in data}
setwd('..')
bc_ai_join = read_csv("data/county_concentrations/joined_dta/bc_ai_join.csv")
no3_ai_join = read_csv("data/county_concentrations/joined_dta/no3_ai_join.csv")
so4_ai_join = read_csv("data/county_concentrations/joined_dta/so4_ai_join.csv")
nh4_ai_join = read_csv("data/county_concentrations/joined_dta/nh4_ai_join.csv")
om_ai_join = read_csv("data/county_concentrations/joined_dta/om_ai_join.csv")
soil_ai_join = read_csv("data/county_concentrations/joined_dta/soil_ai_join.csv")
```

## Sensitivity Analysis: Additionally adjust for geographic region (addition of this variable in model)
This code is almost identical to that found in componentName_analysis.Rmd files, just additionally adjusted for Climate_Zone variable in the linear mixed effects model.

```{r BC lmers}
# full adj model
bc_full_geog = lmer(bc ~ county_type + as.factor(year) + 
                    popd_q + 
                    hhinc_q + Climate_Zone +
                    (1|State/County),
                  data = bc_ai_join, REML=FALSE)

## 95% CI: point estimate, LL, UL
paste(summary(bc_full_geog)$coefficients[2,1] %>% round(digits = 3),
      " (",
      round(summary(bc_full_geog)$coefficients[2,1] - 1.96*summary(bc_full_geog)$coefficients[2,2], digits = 3),
      ", ",
      round(summary(bc_full_geog)$coefficients[2,1] + 1.96*summary(bc_full_geog)$coefficients[2,2], digits = 3),
      ")", sep = "")
paste(summary(bc_full_geog)$coefficients[2,1] %>% round(digits = 2),
      " (",
      round(summary(bc_full_geog)$coefficients[2,1] - 1.96*summary(bc_full_geog)$coefficients[2,2], digits = 2),
      ", ",
      round(summary(bc_full_geog)$coefficients[2,1] + 1.96*summary(bc_full_geog)$coefficients[2,2], digits = 2),
      ")", sep = "")

# fully adjusted with interaction term for year
bc_full_geog_interx = lmer(bc ~ county_type + as.factor(year) + 
                    popd_q + 
                    hhinc_q + Climate_Zone +
                    county_type*as.factor(year) +
                    (1|State/County),
                  data = bc_ai_join, REML=FALSE)
summary(bc_full_geog_interx)
```

```{r BC interX plot from lmer}
# create vcov matrix of main effects and interX

# 8/17/20 edit: first define variable for model function to avoid rerunning it a million times
native_yr_vcov <- vcov(bc_full_geog_interx)[c(2,seq(46,62)), c(2,seq(46,62))]

# calculate all the variances for all the years i.e. var(x+y); should be 19 total entries
var_vector = c()
for (i in 2:18){
  var_vector[1] <- native_yr_vcov[1,1]
  var_vector[i] <- native_yr_vcov[1,1] + native_yr_vcov[i,i] + 2 * native_yr_vcov[i,1]
}
var_vector
sd_vector <- sqrt(var_vector)
length(sd_vector)
#matrix with 19 cols for 19 years, three rows: one for effect estimate of total effect per year (total effect = main effect + interx effect), one for CI lower, one for CI upper
bc_decline_geog <- data.frame()
bc_decline_geog[1,1] <- summary(bc_full_geog_interx)$coefficients[2,1]
bc_decline_geog[1,2] <- summary(bc_full_geog_interx)$coefficients[2,1] - 1.96*sd_vector[1]
bc_decline_geog[1,3] <- summary(bc_full_geog_interx)$coefficients[2,1] + 1.96*sd_vector[1]

# fill in matrix thru loop for every following year
yr_ct <- 46
for (i in 2:18){
  bc_decline_geog[i,1] <- summary(bc_full_geog_interx)$coefficients[2,1]+
    summary(bc_full_geog_interx)$coefficients[yr_ct,1]
  
  bc_decline_geog[i,2] <- summary(bc_full_geog_interx)$coefficients[2,1]+
    summary(bc_full_geog_interx)$coefficients[yr_ct,1] - 1.96*sd_vector[i]
  
  bc_decline_geog[i,3] <- summary(bc_full_geog_interx)$coefficients[2,1]+
    summary(bc_full_geog_interx)$coefficients[yr_ct,1] + 1.96*sd_vector[i]
  yr_ct <- yr_ct + 1
}

bc_decline_geog

colnames(bc_decline_geog) <- c('estimate', 'cl_lower', 'cl_upper') # set col names

bc_decline_geog$year <- seq(2000, 2017) # column for year


#PLOT OF TOTAL EFFECT OF NATIVE OVER TIME; updated 12/14 to be consistent with Figure 3 layout (slanted x-axis label)
bc_geog_interx_plot <- ggplot() + 
  theme_linedraw() + 
  geom_line(data = bc_decline_geog,
            aes(x=year, y = estimate)) +
  geom_line(data=bc_decline_geog,
            aes(x=year, y=cl_lower), linetype = "dashed") +
  geom_line(data=bc_decline_geog,
            aes(x=year, y=cl_upper), linetype = "dashed") +
  ylim(-0.6, 0.6) +
  labs(x = "Year",
       y = expression(paste("Mean Difference in BC (", mu, "g/", m^3, ")")),
       fill = "County Type") +
  theme(plot.title = element_text(size = 18),
        axis.title = element_text(size = 16),
        axis.text = element_text(size = 12),
        axis.title.x=element_blank()) +
  scale_x_continuous(breaks = seq(2000,2017,1), expand = c(0, 0)) +
  guides(x =  guide_axis(angle = 45)) +
  geom_hline(yintercept=0, linetype="solid", color = "red")
bc_geog_interx_plot
bc_decline_geog
ggsave("../figures/effectmod_plots/sensitivity/adj_geog_region/bc.png", width = 6, height = 4, dpi = 300)

```


```{r NH4 lmers}
# full adj model
nh4_full_geog = lmer(nh4 ~ county_type + as.factor(year) + 
                    popd_q + 
                    hhinc_q + Climate_Zone +
                    (1|State/County),
                  data = nh4_ai_join, REML=FALSE)

## 95% CI: point estimate, LL, UL
# paste(summary(nh4_full_geog)$coefficients[2,1] %>% round(digits = 3),
#       " (",
#       round(summary(nh4_full_geog)$coefficients[2,1] - 1.96*summary(nh4_full_geog)$coefficients[2,2], digits = 3),
#       ", ",
#       round(summary(nh4_full_geog)$coefficients[2,1] + 1.96*summary(nh4_full_geog)$coefficients[2,2], digits = 3),
#       ")", sep = "")

paste(summary(nh4_full_geog)$coefficients[2,1] %>% round(digits = 2),
      " (",
      round(summary(nh4_full_geog)$coefficients[2,1] - 1.96*summary(nh4_full_geog)$coefficients[2,2], digits = 2),
      ", ",
      round(summary(nh4_full_geog)$coefficients[2,1] + 1.96*summary(nh4_full_geog)$coefficients[2,2], digits = 2),
      ")", sep = "")

# fully adjusted with interaction term for year
nh4_full_geog_interx = lmer(nh4 ~ county_type + as.factor(year) + 
                    popd_q + 
                    hhinc_q + Climate_Zone +
                    county_type*as.factor(year) +
                    (1|State/County),
                  data = nh4_ai_join, REML=FALSE)
# summary(nh4_full_geog_interx)
```

```{r NH4 interX plot from lmer}
# create vcov matrix of main effects and interX

# 8/17/20 edit: first define variable for model function to avoid rerunning it a million times
native_yr_vcov <- vcov(nh4_full_geog_interx)[c(2,seq(46,62)), c(2,seq(46,62))]

# calculate all the variances for all the years i.e. var(x+y); should be 19 total entries
var_vector = c()
for (i in 2:18){
  var_vector[1] <- native_yr_vcov[1,1]
  var_vector[i] <- native_yr_vcov[1,1] + native_yr_vcov[i,i] + 2 * native_yr_vcov[i,1]
}
var_vector
sd_vector <- sqrt(var_vector)
length(sd_vector)
#matrix with 19 cols for 19 years, three rows: one for effect estimate of total effect per year (total effect = main effect + interx effect), one for CI lower, one for CI upper
nh4_decline_geog <- data.frame()
nh4_decline_geog[1,1] <- summary(nh4_full_geog_interx)$coefficients[2,1]
nh4_decline_geog[1,2] <- summary(nh4_full_geog_interx)$coefficients[2,1] - 1.96*sd_vector[1]
nh4_decline_geog[1,3] <- summary(nh4_full_geog_interx)$coefficients[2,1] + 1.96*sd_vector[1]

# fill in matrix thru loop for every following year
yr_ct <- 46
for (i in 2:18){
  nh4_decline_geog[i,1] <- summary(nh4_full_geog_interx)$coefficients[2,1]+
    summary(nh4_full_geog_interx)$coefficients[yr_ct,1]
  
  nh4_decline_geog[i,2] <- summary(nh4_full_geog_interx)$coefficients[2,1]+
    summary(nh4_full_geog_interx)$coefficients[yr_ct,1] - 1.96*sd_vector[i]
  
  nh4_decline_geog[i,3] <- summary(nh4_full_geog_interx)$coefficients[2,1]+
    summary(nh4_full_geog_interx)$coefficients[yr_ct,1] + 1.96*sd_vector[i]
  yr_ct <- yr_ct + 1
}

nh4_decline_geog

colnames(nh4_decline_geog) <- c('estimate', 'cl_lower', 'cl_upper') # set col names

nh4_decline_geog$year <- seq(2000, 2017) # column for year


#PLOT OF TOTAL EFFECT OF NATIVE OVER TIME; updated 12/14 to be consistent with Figure 3 layout (slanted x-axis label)
nh4_geog_interx_plot <- ggplot() + 
  theme_linedraw() + 
  geom_line(data = nh4_decline_geog,
            aes(x=year, y = estimate)) +
  geom_line(data=nh4_decline_geog,
            aes(x=year, y=cl_lower), linetype = "dashed") +
  geom_line(data=nh4_decline_geog,
            aes(x=year, y=cl_upper), linetype = "dashed") +
  labs(x = "Year",
       y = expression(paste("Mean Difference in ", "NH"[4]^"+", " (", mu, "g/", m^3, ")")),
       fill = "County Type") +
  theme(plot.title = element_text(size = 18),
        axis.title = element_text(size = 16),
        axis.text = element_text(size = 12),
        axis.title.x=element_blank()) +
  scale_x_continuous(breaks = seq(2000,2017,1), expand = c(0, 0)) +
  guides(x =  guide_axis(angle = 45)) + 
  ylim(-0.6, 0.6) +
  geom_hline(yintercept=0, linetype="solid", color = "red")
nh4_geog_interx_plot
nh4_decline_geog
ggsave("../figures/effectmod_plots/sensitivity/adj_geog_region/nh4.png", width = 6, height = 4, dpi = 300)

```



```{r NO3 lmer}
# full adj model
no3_full_geog = lmer(no3 ~ county_type + as.factor(year) + 
                    popd_q + 
                    hhinc_q + Climate_Zone +
                    (1|State/County),
                  data = no3_ai_join, REML=FALSE)

## 95% CI: point estimate, LL, UL
# paste(summary(no3_full_geog)$coefficients[2,1] %>% round(digits = 3),
#       " (",
#       round(summary(no3_full_geog)$coefficients[2,1] - 1.96*summary(no3_full_geog)$coefficients[2,2], digits = 3),
#       ", ",
#       round(summary(no3_full_geog)$coefficients[2,1] + 1.96*summary(no3_full_geog)$coefficients[2,2], digits = 3),
#       ")", sep = "")

paste(summary(no3_full_geog)$coefficients[2,1] %>% round(digits = 2),
      " (",
      round(summary(no3_full_geog)$coefficients[2,1] - 1.96*summary(no3_full_geog)$coefficients[2,2], digits = 2),
      ", ",
      round(summary(no3_full_geog)$coefficients[2,1] + 1.96*summary(no3_full_geog)$coefficients[2,2], digits = 2),
      ")", sep = "")

# fully adjusted with interaction term for year
no3_full_geog_interx = lmer(no3 ~ county_type + as.factor(year) + 
                    popd_q + 
                    hhinc_q + Climate_Zone +
                    county_type*as.factor(year) +
                    (1|State/County),
                  data = no3_ai_join, REML=FALSE)
# summary(no3_full_geog_interx)
```


```{r NO3 interX plot from lmer}
# create vcov matrix of main effects and interX

# 8/17/20 edit: first define variable for model function to avoid rerunning it a million times
native_yr_vcov <- vcov(no3_full_geog_interx)[c(2,seq(46,62)), c(2,seq(46,62))]

# calculate all the variances for all the years i.e. var(x+y); should be 19 total entries
var_vector = c()
for (i in 2:18){
  var_vector[1] <- native_yr_vcov[1,1]
  var_vector[i] <- native_yr_vcov[1,1] + native_yr_vcov[i,i] + 2 * native_yr_vcov[i,1]
}
var_vector
sd_vector <- sqrt(var_vector)
length(sd_vector)
#matrix with 19 cols for 19 years, three rows: one for effect estimate of total effect per year (total effect = main effect + interx effect), one for CI lower, one for CI upper
no3_decline_geog <- data.frame()
no3_decline_geog[1,1] <- summary(no3_full_geog_interx)$coefficients[2,1]
no3_decline_geog[1,2] <- summary(no3_full_geog_interx)$coefficients[2,1] - 1.96*sd_vector[1]
no3_decline_geog[1,3] <- summary(no3_full_geog_interx)$coefficients[2,1] + 1.96*sd_vector[1]

# fill in matrix thru loop for every following year
yr_ct <- 46
for (i in 2:18){
  no3_decline_geog[i,1] <- summary(no3_full_geog_interx)$coefficients[2,1]+
    summary(no3_full_geog_interx)$coefficients[yr_ct,1]
  
  no3_decline_geog[i,2] <- summary(no3_full_geog_interx)$coefficients[2,1]+
    summary(no3_full_geog_interx)$coefficients[yr_ct,1] - 1.96*sd_vector[i]
  
  no3_decline_geog[i,3] <- summary(no3_full_geog_interx)$coefficients[2,1]+
    summary(no3_full_geog_interx)$coefficients[yr_ct,1] + 1.96*sd_vector[i]
  yr_ct <- yr_ct + 1
}

no3_decline_geog

colnames(no3_decline_geog) <- c('estimate', 'cl_lower', 'cl_upper') # set col names

no3_decline_geog$year <- seq(2000, 2017) # column for year


#PLOT OF TOTAL EFFECT OF NATIVE OVER TIME; updated 12/14 to be consistent with Figure 3 layout (slanted x-axis label)
no3_geog_interx_plot <- ggplot() + 
  theme_linedraw() + 
  geom_line(data = no3_decline_geog,
            aes(x=year, y = estimate)) +
  geom_line(data=no3_decline_geog,
            aes(x=year, y=cl_lower), linetype = "dashed") +
  geom_line(data=no3_decline_geog,
            aes(x=year, y=cl_upper), linetype = "dashed") +
  labs(x = "Year",
       y = expression(paste("Mean Difference in ", "NO"[3]^"-", " (", mu, "g/", m^3, ")")),
       fill = "County Type") +
  theme(plot.title = element_text(size = 18),
        axis.title = element_text(size = 16),
        axis.text = element_text(size = 12),
        axis.title.x=element_blank()) +
  scale_x_continuous(breaks = seq(2000,2017,1), expand = c(0, 0)) +
  guides(x =  guide_axis(angle = 45)) + 
  ylim(-0.6, 0.6) +
  geom_hline(yintercept=0, linetype="solid", color = "red")
no3_geog_interx_plot
no3_decline_geog
ggsave("../figures/effectmod_plots/sensitivity/adj_geog_region/no3.png", width = 6, height = 4, dpi = 300)

```

```{r OM lmer}
# full adj model
om_full_geog = lmer(om ~ county_type + as.factor(year) + 
                    popd_q + 
                    hhinc_q + Climate_Zone +
                    (1|State/County),
                  data = om_ai_join, REML=FALSE)

# 95% CI: point estimate, LL, UL
paste(summary(om_full_geog)$coefficients[2,1] %>% round(digits = 3),
      " (",
      round(summary(om_full_geog)$coefficients[2,1] - 1.96*summary(om_full_geog)$coefficients[2,2], digits = 3),
      ", ",
      round(summary(om_full_geog)$coefficients[2,1] + 1.96*summary(om_full_geog)$coefficients[2,2], digits = 3),
      ")", sep = "")

paste(summary(om_full_geog)$coefficients[2,1] %>% round(digits = 2),
      " (",
      round(summary(om_full_geog)$coefficients[2,1] - 1.96*summary(om_full_geog)$coefficients[2,2], digits = 2),
      ", ",
      round(summary(om_full_geog)$coefficients[2,1] + 1.96*summary(om_full_geog)$coefficients[2,2], digits = 2),
      ")", sep = "")

# fully adjusted with interaction term for year
om_full_geog_interx = lmer(om ~ county_type + as.factor(year) + 
                    popd_q + 
                    hhinc_q + Climate_Zone +
                    county_type*as.factor(year) +
                    (1|State/County),
                  data = om_ai_join, REML=FALSE)
# summary(om_full_geog_interx)
```

```{r OM interX plot from lmer}
# create vcov matrix of main effects and interX

# 8/17/20 edit: first define variable for model function to avoid rerunning it a million times
native_yr_vcov <- vcov(om_full_geog_interx)[c(2,seq(46,62)), c(2,seq(46,62))]

# calculate all the variances for all the years i.e. var(x+y); should be 19 total entries
var_vector = c()
for (i in 2:18){
  var_vector[1] <- native_yr_vcov[1,1]
  var_vector[i] <- native_yr_vcov[1,1] + native_yr_vcov[i,i] + 2 * native_yr_vcov[i,1]
}
var_vector
sd_vector <- sqrt(var_vector)
length(sd_vector)
#matrix with 19 cols for 19 years, three rows: one for effect estimate of total effect per year (total effect = main effect + interx effect), one for CI lower, one for CI upper
om_decline_geog <- data.frame()
om_decline_geog[1,1] <- summary(om_full_geog_interx)$coefficients[2,1]
om_decline_geog[1,2] <- summary(om_full_geog_interx)$coefficients[2,1] - 1.96*sd_vector[1]
om_decline_geog[1,3] <- summary(om_full_geog_interx)$coefficients[2,1] + 1.96*sd_vector[1]

# fill in matrix thru loop for every following year
yr_ct <- 46
for (i in 2:18){
  om_decline_geog[i,1] <- summary(om_full_geog_interx)$coefficients[2,1]+
    summary(om_full_geog_interx)$coefficients[yr_ct,1]
  
  om_decline_geog[i,2] <- summary(om_full_geog_interx)$coefficients[2,1]+
    summary(om_full_geog_interx)$coefficients[yr_ct,1] - 1.96*sd_vector[i]
  
  om_decline_geog[i,3] <- summary(om_full_geog_interx)$coefficients[2,1]+
    summary(om_full_geog_interx)$coefficients[yr_ct,1] + 1.96*sd_vector[i]
  yr_ct <- yr_ct + 1
}

om_decline_geog

colnames(om_decline_geog) <- c('estimate', 'cl_lower', 'cl_upper') # set col names

om_decline_geog$year <- seq(2000, 2017) # column for year


#PLOT OF TOTAL EFFECT OF NATIVE OVER TIME; updated 12/14 to be consistent with Figure 3 layout (slanted x-axis label)
om_geog_interx_plot <- ggplot() + 
  theme_linedraw() + 
  geom_line(data = om_decline_geog,
            aes(x=year, y = estimate)) +
  geom_line(data=om_decline_geog,
            aes(x=year, y=cl_lower), linetype = "dashed") +
  geom_line(data=om_decline_geog,
            aes(x=year, y=cl_upper), linetype = "dashed") +
  labs(x = "Year",
       y = expression(paste("Mean Difference in OM (", mu, "g/", m^3, ")")),
       fill = "County Type") +
  theme(plot.title = element_text(size = 18),
        axis.title = element_text(size = 16),
        axis.text = element_text(size = 12),
        axis.title.x=element_blank()) +
  scale_x_continuous(breaks = seq(2000,2017,1), expand = c(0, 0)) +
  guides(x =  guide_axis(angle = 45)) + 
  ylim(-0.6, 0.6) +
  geom_hline(yintercept=0, linetype="solid", color = "red")
om_geog_interx_plot
om_decline_geog
ggsave("../figures/effectmod_plots/sensitivity/adj_geog_region/om.png", width = 6, height = 4, dpi = 300)

```


```{r SO4 lmers}
# full adj model
so4_full_geog = lmer(so4 ~ county_type + as.factor(year) + 
                    popd_q + 
                    hhinc_q + Climate_Zone +
                    (1|State/County),
                  data = so4_ai_join, REML=FALSE)

## 95% CI: point estimate, LL, UL
# paste(summary(so4_full_geog)$coefficients[2,1] %>% round(digits = 3),
#       " (",
#       round(summary(so4_full_geog)$coefficients[2,1] - 1.96*summary(so4_full_geog)$coefficients[2,2], digits = 3),
#       ", ",
#       round(summary(so4_full_geog)$coefficients[2,1] + 1.96*summary(so4_full_geog)$coefficients[2,2], digits = 3),
#       ")", sep = "")

paste(summary(so4_full_geog)$coefficients[2,1] %>% round(digits = 2),
      " (",
      round(summary(so4_full_geog)$coefficients[2,1] - 1.96*summary(so4_full_geog)$coefficients[2,2], digits = 2),
      ", ",
      round(summary(so4_full_geog)$coefficients[2,1] + 1.96*summary(so4_full_geog)$coefficients[2,2], digits = 2),
      ")", sep = "")

# fully adjusted with interaction term for year
so4_full_geog_interx = lmer(so4 ~ county_type + as.factor(year) + 
                    popd_q + 
                    hhinc_q + Climate_Zone +
                    county_type*as.factor(year) +
                    (1|State/County),
                  data = so4_ai_join, REML=FALSE)
# summary(so4_full_geog_interx)
```


```{r SO4 interX plot from lmer}
# create vcov matrix of main effects and interX

# 8/17/20 edit: first define variable for model function to avoid rerunning it a million times
native_yr_vcov <- vcov(so4_full_geog_interx)[c(2,seq(46,62)), c(2,seq(46,62))]

# calculate all the variances for all the years i.e. var(x+y); should be 19 total entries
var_vector = c()
for (i in 2:18){
  var_vector[1] <- native_yr_vcov[1,1]
  var_vector[i] <- native_yr_vcov[1,1] + native_yr_vcov[i,i] + 2 * native_yr_vcov[i,1]
}
var_vector
sd_vector <- sqrt(var_vector)
length(sd_vector)
# matrix with 19 cols for 19 years, three rows: one for effect estimate of total effect per year (total effect = main effect + interx effect), one for CI lower, one for CI upper
# first year (baseline 2000)
so4_decline_geog <- data.frame()
so4_decline_geog[1,1] <- summary(so4_full_geog_interx)$coefficients[2,1]
so4_decline_geog[1,2] <- summary(so4_full_geog_interx)$coefficients[2,1] - 1.96*sd_vector[1]
so4_decline_geog[1,3] <- summary(so4_full_geog_interx)$coefficients[2,1] + 1.96*sd_vector[1]

# fill in matrix thru loop for every following year
yr_ct <- 46
for (i in 2:18){
  so4_decline_geog[i,1] <- summary(so4_full_geog_interx)$coefficients[2,1]+
    summary(so4_full_geog_interx)$coefficients[yr_ct,1]
  
  so4_decline_geog[i,2] <- summary(so4_full_geog_interx)$coefficients[2,1]+
    summary(so4_full_geog_interx)$coefficients[yr_ct,1] - 1.96*sd_vector[i]
  
  so4_decline_geog[i,3] <- summary(so4_full_geog_interx)$coefficients[2,1]+
    summary(so4_full_geog_interx)$coefficients[yr_ct,1] + 1.96*sd_vector[i]
  yr_ct <- yr_ct + 1
}

so4_decline_geog

colnames(so4_decline_geog) <- c('estimate', 'cl_lower', 'cl_upper') # set col names

so4_decline_geog$year <- seq(2000, 2017) # column for year


#PLOT OF TOTAL EFFECT OF NATIVE OVER TIME; updated 12/14 to be consistent with Figure 3 layout (slanted x-axis label)
so4_geog_interx_plot <- ggplot() + 
  theme_linedraw() + 
  geom_line(data = so4_decline_geog,
            aes(x=year, y = estimate)) +
  geom_line(data=so4_decline_geog,
            aes(x=year, y=cl_lower), linetype = "dashed") +
  geom_line(data=so4_decline_geog,
            aes(x=year, y=cl_upper), linetype = "dashed") +
  labs(x = "Year",
       y = expression(paste("Mean Difference in ", "SO"[4]^"2-", " (", mu, "g/", m^3, ")")),
       fill = "County Type") +
  theme(plot.title = element_text(size = 18),
        axis.title = element_text(size = 16),
        axis.text = element_text(size = 12),
        axis.title.x=element_blank()) +
  scale_x_continuous(breaks = seq(2000,2017,1), expand = c(0, 0)) +
  guides(x =  guide_axis(angle = 45)) + 
  ylim(-0.6, 0.6) +
  geom_hline(yintercept=0, linetype="solid", color = "red")
so4_geog_interx_plot
so4_decline_geog
ggsave("../figures/effectmod_plots/sensitivity/adj_geog_region/so4.png", width = 6, height = 4, dpi = 300)

```


```{r Soil lmer}
# full adj model
soil_full_geog = lmer(soil ~ county_type + as.factor(year) + 
                    popd_q + 
                    hhinc_q + Climate_Zone +
                    (1|State/County),
                  data = soil_ai_join, REML=FALSE)

## 95% CI: point estimate, LL, UL
# paste(summary(soil_full_geog)$coefficients[2,1] %>% round(digits = 3),
#       " (",
#       round(summary(soil_full_geog)$coefficients[2,1] - 1.96*summary(soil_full_geog)$coefficients[2,2], digits = 3),
#       ", ",
#       round(summary(soil_full_geog)$coefficients[2,1] + 1.96*summary(soil_full_geog)$coefficients[2,2], digits = 3),
#       ")", sep = "")

paste(summary(soil_full_geog)$coefficients[2,1] %>% round(digits = 2),
      " (",
      round(summary(soil_full_geog)$coefficients[2,1] - 1.96*summary(soil_full_geog)$coefficients[2,2], digits = 2),
      ", ",
      round(summary(soil_full_geog)$coefficients[2,1] + 1.96*summary(soil_full_geog)$coefficients[2,2], digits = 2),
      ")", sep = "")

# fully adjusted with interaction term for year
soil_full_geog_interx = lmer(soil ~ county_type + as.factor(year) + 
                    popd_q + 
                    hhinc_q + Climate_Zone +
                    county_type*as.factor(year) +
                    (1|State/County),
                  data = soil_ai_join, REML=FALSE)
# summary(soil_full_geog_interx)
```


```{r Soil interX plot from lmer}
# create vcov matrix of main effects and interX

# 8/17/20 edit: first define variable for model function to avoid rerunning it a million times
native_yr_vcov <- vcov(soil_full_geog_interx)[c(2,seq(46,62)), c(2,seq(46,62))]

# calculate all the variances for all the years i.e. var(x+y); should be 19 total entries
var_vector = c()
for (i in 2:18){
  var_vector[1] <- native_yr_vcov[1,1]
  var_vector[i] <- native_yr_vcov[1,1] + native_yr_vcov[i,i] + 2 * native_yr_vcov[i,1]
}
var_vector
sd_vector <- sqrt(var_vector)
length(sd_vector)
#matrix with 19 cols for 19 years, three rows: one for effect estimate of total effect per year (total effect = main effect + interx effect), one for CI lower, one for CI upper
soil_decline_geog <- data.frame()
soil_decline_geog[1,1] <- summary(soil_full_geog_interx)$coefficients[2,1]
soil_decline_geog[1,2] <- summary(soil_full_geog_interx)$coefficients[2,1] - 1.96*sd_vector[1]
soil_decline_geog[1,3] <- summary(soil_full_geog_interx)$coefficients[2,1] + 1.96*sd_vector[1]

# fill in matrix thru loop for every following year
yr_ct <- 46
for (i in 2:18){
  soil_decline_geog[i,1] <- summary(soil_full_geog_interx)$coefficients[2,1]+
    summary(soil_full_geog_interx)$coefficients[yr_ct,1]
  
  soil_decline_geog[i,2] <- summary(soil_full_geog_interx)$coefficients[2,1]+
    summary(soil_full_geog_interx)$coefficients[yr_ct,1] - 1.96*sd_vector[i]
  
  soil_decline_geog[i,3] <- summary(soil_full_geog_interx)$coefficients[2,1]+
    summary(soil_full_geog_interx)$coefficients[yr_ct,1] + 1.96*sd_vector[i]
  yr_ct <- yr_ct + 1
}

soil_decline_geog

colnames(soil_decline_geog) <- c('estimate', 'cl_lower', 'cl_upper') # set col names

soil_decline_geog$year <- seq(2000, 2017) # column for year


#PLOT OF TOTAL EFFECT OF NATIVE OVER TIME; updated 12/14 to be consistent with Figure 3 layout (slanted x-axis label)
soil_geog_interx_plot <- ggplot() + 
  theme_linedraw() + 
  geom_line(data = soil_decline_geog,
            aes(x=year, y = estimate)) +
  geom_line(data=soil_decline_geog,
            aes(x=year, y=cl_lower), linetype = "dashed") +
  geom_line(data=soil_decline_geog,
            aes(x=year, y=cl_upper), linetype = "dashed") +
  labs(x = "Year",
       y = expression(paste("Mean Difference in Mineral Dust (", mu, "g/", m^3, ")")),
       fill = "County Type") +
  theme(plot.title = element_text(size = 18),
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        axis.title.x=element_blank()) +
  scale_x_continuous(breaks = seq(2000,2017,1), expand = c(0, 0)) +
  guides(x =  guide_axis(angle = 45)) + 
  ylim(-0.6, 0.6) +
  geom_hline(yintercept=0, linetype="solid", color = "red")
soil_geog_interx_plot
soil_decline_geog
ggsave("../figures/effectmod_plots/sensitivity/adj_geog_region/soil.png", width = 6, height = 4, dpi = 300)

```

```{r Write a for loop to do this; in progress!}
# # loop through the dfs of 6 different components
# comp_list = list(nh4_ai_join,
#                  so4_ai_join,
#                  no3_ai_join,
#                  bc_ai_join,
#                  om_ai_join,
#                  soil_ai_join)
# comp_names = c("nh4", "so4", "no3", "bc", "om", "soil")
# comp_list[1]
# # empty lists to save the lmer model outputs into (main effects only and with county type x year interaction)
# # comp_maineffects = list()
# # comp_interx = list()
# 
# # empty list to save df of the effect estimates and CI, for each study year, outputted from lmer with interX, to plot
# comp_decline = list()
# 
# 
# for (comp in 1:6){
#     # rename component column names to be the same in order to run lmer
#   comp_list[[comp]] = comp_list[[comp]] %>% 
#     rename(comp = comp_names[comp])
#   # run lmer main effects only
#   comp_maineffects = lmer(comp ~ county_type + as.factor(year) + 
#                     popd_q + 
#                     hhinc_q + Climate_Zone +
#                     (1|State/County),
#                   data = comp_list[[comp]], REML=FALSE) 
#   
#   ## 95% CI: point estimate, LL, UL
#   paste(summary(comp_maineffects)$coefficients[2,1] %>% round(digits = 3),
#         " (",
#         round(summary(comp_maineffects)$coefficients[2,1] - 1.96*summary(comp_maineffects)$coefficients[2,2], digits = 3),
#         ", ",
#         round(summary(comp_maineffects)$coefficients[2,1] + 1.96*summary(comp_maineffects)$coefficients[2,2], digits = 3),
#         ")", sep = "")
#   paste(summary(comp_maineffects)$coefficients[2,1] %>% round(digits = 2),
#         " (",
#         round(summary(comp_maineffects)$coefficients[2,1] - 1.96*summary(comp_maineffects)$coefficients[2,2], digits = 2),
#         ", ",
#         round(summary(comp_maineffects)$coefficients[2,1] + 1.96*summary(comp_maineffects)$coefficients[2,2], digits = 2),
#         ")", sep = "")
#   
#   # fully adjusted lmer with interaction term for year x county type
#   comp_interx = lmer(comp ~ county_type + as.factor(year) + 
#                       popd_q + 
#                       hhinc_q + Climate_Zone +
#                       county_type*as.factor(year) +
#                       (1|State/County),
#                     data = comp_list[[comp]], REML=FALSE)
#   # create vcov matrix of main effects and interX
#   native_yr_vcov <- vcov(comp_interx)[c(2,seq(46,62)), c(2,seq(46,62))]
#   
#   # calculate all the variances for all the years i.e. var(x+y); should be 19 total entries
#   var_vector = c()
#   for (i in 2:18){
#     var_vector[1] <- native_yr_vcov[1,1]
#     var_vector[i] <- native_yr_vcov[1,1] + native_yr_vcov[i,i] + 2 * native_yr_vcov[i,1]
#   }
#   
#   var_vector
#   sd_vector <- sqrt(var_vector)
#   length(sd_vector)
#   #matrix with 19 cols for 19 years, three rows: one for effect estimate of total effect per year (total effect = main effect + interx effect), one for CI lower, one for CI upper
#   comp_decline[[comp]] <- data.frame()
#   comp_decline[[comp]][1,1] <- summary(comp_interx)$coefficients[2,1]
#   comp_decline[[comp]][1,2] <- summary(comp_interx)$coefficients[2,1] - 1.96*sd_vector[1]
#   comp_decline[[comp]][1,3] <- summary(comp_interx)$coefficients[2,1] + 1.96*sd_vector[1]
#   
#   # fill in matrix thru loop for every following year
#   yr_ct <- 46
#   for (i in 2:18){
#     comp_decline[[i]][i,1] <- summary(comp_interx)$coefficients[2,1]+
#       summary(comp_interx)$coefficients[yr_ct,1]
#     
#     comp_decline[[i]][i,2] <- summary(comp_interx)$coefficients[2,1]+
#       summary(comp_interx)$coefficients[yr_ct,1] - 1.96*sd_vector[i]
#     
#     comp_decline[[i]][i,3] <- summary(comp_interx)$coefficients[2,1]+
#       summary(comp_interx)$coefficients[yr_ct,1] + 1.96*sd_vector[i]
#     yr_ct <- yr_ct + 1
#   }
#   
#   comp_decline[[comp]]
#   
#   colnames(comp_decline[[comp]]) <- c('estimate', 'cl_lower', 'cl_upper') # set col names
#   
#   comp_decline[[comp]]$year <- seq(2000, 2017) # column for year
#   
#   
#   # #PLOT OF TOTAL EFFECT OF NATIVE OVER TIME; updated 12/14 to be consistent with Figure 3 layout (slanted x-axis label)
#   # geog_interx_plot <- ggplot() + 
#   #   theme_linedraw() + 
#   #   geom_line(data = comp_decline[[i]],
#   #             aes(x=year, y = estimate)) +
#   #   geom_line(data=comp_decline[[i]],
#   #             aes(x=year, y=cl_lower), linetype = "dashed") +
#   #   geom_line(data=comp_decline[[i]],
#   #             aes(x=year, y=cl_upper), linetype = "dashed") +
#   #   labs(x = "Year",
#   #        y = expression(paste("Mean Difference in BC (", mu, "g/", m^3, ")")),
#   #        fill = "County Type") +
#   #   theme(plot.title = element_text(size = 18),
#   #         axis.title = element_text(size = 16),
#   #         axis.text = element_text(size = 12),
#   #         axis.title.x=element_blank()) +
#   #   scale_x_continuous(breaks = seq(2000,2017,1), expand = c(0, 0)) +
#   #   guides(x =  guide_axis(angle = 45)) + ylim(-0.6, 0.6) +
#   #   geom_hline(yintercept=0, linetype="solid", color = "red")
#   # geog_interx_plot
#   # ggsave(plot = geog_interx_plot, filename = paste('../figures/effectmod_plots/sensitivity/adj_geog_region/', comp_names[i], 'png', width = 6, height = 4, dpi = 300))
# 
# }
# comp_decline
```
